# Generated by Django 6.0.3 on 2026-03-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='name',
        ),
        migrations.AddField(
            model_name='dish',
            name='description_ar',
            field=models.TextField(default=1, verbose_name='الوصف بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='description_en',
            field=models.TextField(default=1, verbose_name='الوصف بالإنجليزي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='name_ar',
            field=models.CharField(default=1, max_length=100, verbose_name='الاسم بالعربي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='الاسم بالإنجليزي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default=1, upload_to='dishes/', verbose_name='الصورة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر'),
        ),
    ]
